AWSTemplateFormatVersion: 2010-09-09
Description: Creates S3 buckets for PaperTool
Metadata:
    Generator: "papertool"

# Custom params that the user can define at the time of stack creation
# RePEc:aaa:ssssss, where aaa is the archive code and ssssss is the series
# code. NOTE: Ensure that bucket names are unique across AWS.
# Rules:
# 1. No uppercase letters. Only lower case and hyphen.
# 2. E.g. if SiteBuckeName is provided as `econdept` and ArchiveCode is `mos`,
#   a. Site bucket: econdept-mos
#   b. Working Paper bucket: econdept-mos-archive
#   c. Lambda Function bucket: econdept-mos-lambda
Parameters:
  SiteBucketName:
    Type: String
  ArchiveCode:
    Type: String
  # SeriesCode:
  #   Type: String

Resources:
  # S3 bucket definitions
  # 1. SiteBucket: Used for hosting the main working papers site
  # accessible via: ...
  SiteBucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket for hosting Working papers site
    Properties:
      BucketName: !Sub ${SiteBucketName}-${ArchiveCode}
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"
      Tags:
      -
        Key: "created_by"
        Value: "papertool"
  
  WorkingPapersBucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket for storing working papers
    Properties:
      BucketName: !Sub ${SiteBucketName}-${ArchiveCode}-archive
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
      -
        Key: "created_by"
        Value: "sodalabs"

  # 3. LambdaFunctionBucket: S3 Bucket to store the uploadPaper Lambda function
  LambdaFunctionBucket:
      Type: AWS::S3::Bucket
      Description: Creating Amazon S3 bucket for storing UploadPaper Lambda function
      Properties:
        BucketName: !Sub ${SiteBucketName}-${ArchiveCode}-lambda # name of the S3 bucket
        VersioningConfiguration:
          Status: Enabled
        AccessControl: Private
        Tags:
        -
          Key: "created_by"
          Value: "sodalabs"
      
  # S3 bucket policies
  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${SiteBucket}/*
            Principal:
              AWS:
                - '*'
  
  WorkingPapersBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WorkingPapersBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${WorkingPapersBucket}/*
            Principal:
              AWS:
                - '*'
  LambdaFunctionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaFunctionBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${LambdaFunctionBucket}/*
            Principal:
              Service:
                - cloudformation.amazonaws.com

Outputs:
  SiteBucket:
    Description: Name of the S3 site bucket.
    Value: !Ref SiteBucket

  WorkingPapersBucket:
    Description: Name of the S3 working papers archive.
    Value: !Ref WorkingPapersBucket
  
  LambdaFunctionBucket:
    Description: Name of the Lambda function code respository.
    Value: !Ref LambdaFunctionBucket

  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
    Description: URL for the working papers website hosted on S3.