AWSTemplateFormatVersion: 2010-09-09
Description: Creates S3 buckets for PaperTool
Metadata:
    Generator: "SoDa Labs"
    Author: "satyaborg"

# Custom params that the user can define at the time of stack creation
# RePEc:aaa:ssssss, where aaa is the archive code and ssssss is the series
# code. NOTE: Ensure that bucket names are unique across AWS.
Parameters:
  SiteBucketName:
    Description: "Please enter your preferred name for the S3 bucket. This will be part of the name for your working paper website (Note: Bucket names MUST be unique across AWS and no Upper Case characters are allowed)"
    Type: String
  ArchiveCode:
    Description: "Please enter your 3-letter RePEc code for the archive."
    Type: String
  SeriesCode:
    Description: "Please enter your 6-letter RePEc code for the series."
    Type: String

Outputs:
  ArchiveCode:
    Description: 3-letter archive code
    Value: !Ref ArchiveCode
  
  SeriesCode:
    Description: 6-letter series code
    Value: !Ref SeriesCode
  
  SiteBucket:
    Description: Name of the S3 site bucket.
    Value: !Ref SiteBucket

  WorkingPapersBucket:
    Description: Name of the S3 working papers archive.
    Value: !Ref WorkingPapersBucket
  
  CodeBucket:
    Description: Name of the Lambda function code respository.
    Value: !Ref CodeBucket
    Export:
      Name: CodeBucket
      Value: !Ref CodeBucket

  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
    Description: URL for the working papers website hosted on S3.
  
  RePEcArchiveURL:
    Value: !GetAtt WorkingPapersBucket.WebsiteURL
    Description: URL for RePEc archive hosted on S3 that RePEc requires.

  AWSRegion:
    Value: !Ref AWS::Region
    Description: Name of your current AWS region.
  
  RePEcHandle:
    Value: !Sub RePEc:${ArchiveCode}:${SeriesCode}
    Description: The RePEc handle for your working paper series

  TemplateURL:
    Value: !Sub https://${SiteBucketName}-${ArchiveCode}-archive.s3.${AWS::Region}.amazonaws.com/template/cover.png
    Description: "The URL for your working paper front-page template. Note: It should be named 'cover.png' or change the URL accordingly."

Resources:
  # S3 bucket definitions
  # 1. SiteBucket: Used for hosting the main working papers site
  # accessible via: ...
  SiteBucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket for hosting Working papers site
    Properties:
      BucketName: !Sub ${SiteBucketName}-${ArchiveCode}-site
      # VersioningConfiguration:
      #   Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            # ExposeHeaders:
            #   - []
            MaxAge: '3000'
  
  WorkingPapersBucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket for storing working papers
    Properties:
      BucketName: !Sub ${SiteBucketName}-${ArchiveCode}-archive
      # VersioningConfiguration:
      #   Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            # ExposeHeaders:
            #   - []
            MaxAge: '3000'

  # 3. CodeBucket: S3 Bucket to store the uploadPaper Lambda function
  CodeBucket:
      Type: AWS::S3::Bucket
      Description: Creating Amazon S3 bucket for storing UploadPaper Lambda function
      Properties:
        BucketName: !Sub ${SiteBucketName}-${ArchiveCode}-code # name of the S3 bucket
        # VersioningConfiguration:
        #   Status: Enabled
        AccessControl: Private
      
  # S3 bucket policies
  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${SiteBucket}/*
            Principal:
              AWS:
                - '*'
  
  WorkingPapersBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WorkingPapersBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${WorkingPapersBucket}/*
            Principal:
              AWS:
                - '*'
          -
            Action:
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${WorkingPapersBucket}
            Principal:
              AWS:
                - '*'
  LambdaFunctionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodeBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${CodeBucket}/*
            Principal:
              Service:
                - cloudformation.amazonaws.com

  # S3ConfigObject:
  #   Type: AWS::S3::Object
  #   Properties:
  #     Target:
  #       Bucket: !Ref CodeBucket
  #       Key: config.json
  #       ContentType: application/json
  #     Body: !Sub |
  #       {
  #         archiveCode: ${ArchiveCode},
  #         seriesCode: ${SeriesCode},
  #         repecHandle: RePEc:${ArchiveCode}:${SeriesCode},
  #         siteBucket: ${SiteBucket}, 
  #         workingPaperBucket: ${WorkingPapersBucket},
  #         bucketRegion: ${AWS::Region},
  #         template_url: https://${SiteBucketName}-${ArchiveCode}-archive.s3.${AWS::Region}.amazonaws.com/template/cover.png
  #       }
